In [2]:
import tensorflow as tf
print(tf.__version__)

2.20.0


In [3]:
import tensorflow as tf
import numpy as np

# Create from NumPy array
a = np.array([1, 2, 3], dtype=np.int32)
t_a = tf.convert_to_tensor(a)

# Create from Python list
b = [4, 5, 6]
t_b = tf.convert_to_tensor(b)

print(t_a)
print(t_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [4]:
# Create a 2x3 matrix of ones
t_ones = tf.ones((2, 3))

# Create a constant tensor
const_tensor = tf.constant([1.2, 5, np.pi], dtype=tf.float32)

# Create a 2x3 matrix filled with a specific value (e.g., 1)
t_fill = tf.fill((2, 3), 1)

print(t_ones.numpy())
print(t_fill.numpy())

[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]


In [5]:
# Change data type to int64
t_a_new = tf.cast(t_a, tf.int64)

# Transpose a matrix (swap rows and columns)
t = tf.random.uniform(shape=(3, 5))
t_tr = tf.transpose(t)

print(t.shape, '-->', t_tr.shape) # (3, 5) --> (5, 3)

(3, 5) --> (5, 3)


In [6]:
tf.random.set_seed(1)
t1 = tf.random.uniform(shape=(5, 2), minval=-1.0, maxval=1.0)
t2 = tf.random.normal(shape=(5, 2), mean=0.0, stddev=1.0)

# Element-wise multiplication
t3 = tf.multiply(t1, t2).numpy()

# Calculate Mean
t4 = tf.math.reduce_mean(t1, axis=0)

print(t3)
print(t4)

[[-0.26996338 -0.87363994]
 [-0.01652772 -0.17496566]
 [-0.296179   -0.13944866]
 [-0.7272108   0.13463594]
 [-0.40087393  0.00445268]]
tf.Tensor([0.08957257 0.2074099 ], shape=(2,), dtype=float32)


In [7]:
tf.random.set_seed(1)
t1 = tf.random.uniform(shape=(5, 2), minval=-1.0, maxval=1.0)
t2 = tf.random.normal(shape=(5, 2), mean=0.0, stddev=1.0)

# Element-wise multiplication
t3 = tf.multiply(t1, t2).numpy()

# Calculate Mean
t4 = tf.math.reduce_mean(t1, axis=0)

print(t3)
print(t4)

[[-0.26996338 -0.87363994]
 [-0.01652772 -0.17496566]
 [-0.296179   -0.13944866]
 [-0.7272108   0.13463594]
 [-0.40087393  0.00445268]]
tf.Tensor([0.08957257 0.2074099 ], shape=(2,), dtype=float32)


In [8]:
t = tf.random.uniform((6,))
t_splits = tf.split(t, 3) # Split into 3 equal parts

[item.numpy() for item in t_splits]

[array([0.8292774, 0.634228 ], dtype=float32),
 array([0.5147276 , 0.39108086], dtype=float32),
 array([0.5809028 , 0.04848182], dtype=float32)]

In [9]:
A = tf.ones((3,))
B = tf.zeros((3,))

# Concat: Joins along an existing axis (extends length)
C = tf.concat([A, B], axis=0) 
# Output: [1. 1. 1. 0. 0. 0.]

# Stack: Joins along a new axis (creates a matrix)
S = tf.stack([A, B], axis=1)
# Output: [[1. 0.], [1. 0.], [1. 0.]]

In [10]:
a = [1.2, 3.4, 7.5, 4.1, 5.0, 1.0]
ds = tf.data.Dataset.from_tensor_slices(a)

# Batching data (e.g., batch size 3)
ds_batch = ds.batch(3)

for i, elem in enumerate(ds_batch, 100):
    print('batch {}'.format(i), elem.numpy())

batch 100 [1.2 3.4 7.5]
batch 101 [4.1 5.  1. ]


In [11]:
# Create data (X) and labels (y)
X = tf.random.uniform([4, 3], dtype=tf.float32)
t_y = tf.range(4)

# Create datasets
ds_x = tf.data.Dataset.from_tensor_slices(X)
ds_y = tf.data.Dataset.from_tensor_slices(t_y)

# Zip them together
ds_joint = tf.data.Dataset.zip((ds_x, ds_y))

for example in ds_joint:
    print('x:', example[0].numpy(), 'y:', example[1].numpy())

x: [0.2364521  0.23877335 0.50363123] y: 0
x: [0.77354    0.61077476 0.8721783 ] y: 1
x: [0.2728473  0.6183162  0.20251584] y: 2
x: [0.8700757  0.4924059  0.49692988] y: 3
