In [ ]:
import numpy as np

# ### Ejercicio 1 – Indexación básica en 1D
print("--- Ejercicio 1: Indexación básica ---")
a = np.arange(2, 41, 2) 
print(f"Array 'a': {a}")

--- Ejercicio 1: Indexación básica ---
Array 'a': [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [ ]:
# 2. Cambia el valor del quinto elemento (índice 4) a 999
a[4] = 999
print(f"Array 'a' modificado: {a}")

# 3. Comprueba el tamaño. 
# En NumPy, el tamaño (size) es fijo una vez creado el array. No cambia al modificar valores.
print(f"Tamaño de 'a': {a.size} (El tamaño es fijo y no cambia)")



In [ ]:
# ### Ejercicio 2 – Slicing con pasos
print("\n--- Ejercicio 2: Slicing con pasos ---")
# 1. Subarray con los 5 primeros elementos [0:5]
print(f"5 primeros: {a[:5]}")

# 2. Subarray con elementos en posiciones pares 
print(f"Posiciones pares: {a[::2]}")

# 3. Subarray posiciones 3 a 10 
print(f"Posiciones 3 a 10: {a[3:10]}")

# 4. Array en orden inverso [::-1]
print(f"Orden inverso: {a[::-1]}")



--- Ejercicio 2: Slicing con pasos ---
5 primeros: [ 2  4  6  8 10]
Posiciones pares: [ 2  6 10 14 18 22 26 30 34 38]
Posiciones 3 a 10: [ 8 10 12 14 16 18 20]
Orden inverso: [40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10  8  6  4  2]


In [ ]:
# ### Ejercicio 3 – Slicing en 2D
print("\n--- Ejercicio 3: Slicing en 2D ---")
# Matriz 5x6 con valores del 0 al 29
M = np.arange(30).reshape(5, 6)
print(f"Matriz M:\n{M}")

# 1. Segunda fila completa (índice 1)
print(f"2da fila completa: {M[1, :]}")
#para que sirve M[1]?
#M[1] también devuelve la segunda fila completa.

# 2. Columna 4 completa
print(f"Columna 4 completa: {M[:, 4]}")

# 3. Subarray filas 1 a 3 (excluye 4) y columnas 2 a 5 (excluye 6)
# Recuerda: en slicing el límite superior es exclusivo.
print(f"Subarray (filas 1-3, cols 2-5):\n{M[1:4, 2:6]}")

# 4. Filas alternas (0,2,4) y columnas alternas (1,3,5) usando steps [::2]
print(f"Filas/Cols alternas:\n{M[::2, 1::2]}")




--- Ejercicio 3: Slicing en 2D ---
Matriz M:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
2da fila completa: [ 6  7  8  9 10 11]
Columna 4 completa: [ 4 10 16 22 28]
Subarray (filas 1-3, cols 2-5):
[[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]]
Filas/Cols alternas:
[[ 1  3  5]
 [13 15 17]
 [25 27 29]]


In [4]:
# ### Ejercicio 4 – Indexación booleana
print("\n--- Ejercicio 4: Indexación booleana ---")
# 1. Máscara booleana para elementos > 15
mask = M > 15
print(f"Máscara (>15):\n{mask}")

# 2. Obtener elementos usando la máscara (devuelve array 1D)
print(f"Elementos >15: {M[mask]}")

# 3. Sustituir por -1 los múltiplos de 3
# Usamos .copy() para no modificar la M original si la necesitáramos después (buena práctica)
M2 = M.copy()
# La condición es (M2 % 3 == 0)
M2[M2 % 3 == 0] = -1
print(f"M2 (Múltiplos de 3 a -1):\n{M2}")



--- Ejercicio 4: Indexación booleana ---
Máscara (>15):
[[False False False False False False]
 [False False False False False False]
 [False False False False  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
Elementos >15: [16 17 18 19 20 21 22 23 24 25 26 27 28 29]
M2 (Múltiplos de 3 a -1):
[[-1  1  2 -1  4  5]
 [-1  7  8 -1 10 11]
 [-1 13 14 -1 16 17]
 [-1 19 20 -1 22 23]
 [-1 25 26 -1 28 29]]


In [8]:
# ### Ejercicio 5 – Fancy indexing
print("\n--- Ejercicio 5: Fancy indexing ---")
# Array b con cuadrados del 1 al 15
b = np.arange(1, 16)**2
print(f"Array 'b': {b}")

# 1. Obtener elementos en índices específicos usando una lista
indices = [0, 3, 5, 10, 14]
print(f"Elementos en índices {indices}: {b[indices]}")
#b[indices] devuelve un array con los elementos en las posiciones dadas por la lista 'indices'.

# 2. Elementos en posiciones impares (índices 1, 3, 5...)
c = b[1::2]
#c[1::2] devuelve un array con los elementos en las posiciones impares del array 'b'.
#[1::2] significa empezar en el índice 1 y tomar cada segundo elemento (índices impares).
print(f"Array 'c' (posiciones impares): {c}")

# 3. Modificar elementos en índices específicos
indices_mod = [1, 4, 7, 10, 13]
b[indices_mod] = 0
print(f"Array 'b' modificado (ceros en índices dados): {b}")

#ejericio por mi cuenta
# Leemos: "En 'b', donde (b % 2 sea 0), pon un 0"
b[b % 2 == 0] = 0
print(f"Array 'b' modificado (ceros en pares): {b}")



--- Ejercicio 5: Fancy indexing ---
Array 'b': [  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225]
Elementos en índices [0, 3, 5, 10, 14]: [  1  16  36 121 225]
Array 'c' (posiciones impares): [  4  16  36  64 100 144 196]
Array 'b' modificado (ceros en índices dados): [  1   0   9  16   0  36  49   0  81 100   0 144 169   0 225]
Array 'b' modificado (ceros en pares): [  1   0   9   0   0   0  49   0  81   0   0   0 169   0 225]


In [6]:
# ### Ejercicio 6 – Combinando boolean y fancy
print("\n--- Ejercicio 6: np.where ---")
# 1. Máscara para mayores de 50
mask_b = b > 50
print(f"Máscara (>50): {mask_b}")

# 2. Obtener los índices donde es True usando np.where()
# np.where(condicion) devuelve una tupla de arrays de índices
indices_b = np.where(mask_b)
print(f"Índices >50: {indices_b[0]}") # Accedemos al primer elemento de la tupla

# 3. Crear nuevo array 'd' con np.where(condicion, valor_si_true, valor_si_false)
d = np.where(b > 50, b, -1)
print(f"Array 'd' (np.where): {d}")



--- Ejercicio 6: np.where ---
Máscara (>50): [False False False False False False False False  True  True False  True
  True False  True]
Índices >50: [ 8  9 11 12 14]
Array 'd' (np.where): [ -1  -1  -1  -1  -1  -1  -1  -1  81 100  -1 144 169  -1 225]


In [ ]:

# ### Ejercicio 7 – Indexación en 3D
print("\n--- Ejercicio 7: Indexación 3D ---")
# Array 3D (3 bloques, 4 filas, 5 columnas)
T = np.arange(60).reshape(3, 4, 5)
print(f"Array T shape: {T.shape}")

# 1. Primer bloque completo (índice 0)
print(f"Primer bloque completo:\n{T[0]}")

# 2. Última fila de CADA bloque.
# Sintaxis: [bloques, filas, columnas] -> [:, -1, :]
print(f"Última fila de cada bloque:\n{T[:, -1, :]}")

# 3. Elementos con última coordenada par (columnas 0, 2, 4)
print(f"Última coordenada par:\n{T[:, :, ::2]}")

# 4. Modificar bloque central (índice 1) a -10
T[1] = -10
print(f"Bloque central modificado (-10):\n{T[1]}")



In [ ]:
# ### Ejercicio 8 – Transposición básica en 2D
print("\n--- Ejercicio 8: Transposición 2D ---")
# Matriz 3x5 valores 10 al 24
A = np.arange(10, 25).reshape(3, 5)
print(f"Matriz A:\n{A}")

# Transpuesta .T
A_T = A.T
print(f"Transpuesta A_T:\n{A_T}")
print(f"Shape A: {A.shape}, Shape A_T: {A_T.shape}") # Se invierten (3,5) -> (5,3)

# Producto matricial @ (o np.dot)
# (3x5) @ (5x3) -> Resultado (3x3)
prod = A @ A_T
print(f"Producto A @ A_T:\n{prod}")
print(f"Shape producto: {prod.shape}")


In [ ]:

# ### Ejercicio 9 – Transposición para facilitar operaciones
print("\n--- Ejercicio 9: Operaciones con Transposición ---")
np.random.seed(42) # Para reproducibilidad
B = np.random.randint(0, 10, (4, 3))
print(f"Matriz B:\n{B}")

# Suma por filas (axis=1) y columnas (axis=0)
print(f"Suma por filas: {B.sum(axis=1)}")
print(f"Suma por columnas: {B.sum(axis=0)}")

# Suma por columnas usando transpuesta
# Si transponemos B -> B.T es (3, 4). Las columnas originales ahora son filas.
# Sumar las columnas originales equivale a sumar las filas de la transpuesta.
suma_cols_directa = B.sum(axis=0)
suma_cols_transpuesta = B.T.sum(axis=1) 

print(f"Suma directa: {suma_cols_directa}")
print(f"Suma transpuesta: {suma_cols_transpuesta}")
print(f"¿Coinciden? {np.array_equal(suma_cols_directa, suma_cols_transpuesta)}")


In [ ]:

# ### Ejercicio 10 – Intercambio de ejes en 3D con `swapaxes`
print("\n--- Ejercicio 10: swapaxes ---")
X = np.arange(24).reshape(2, 3, 4)
print(f"X shape: {X.shape}")

# 1. Intercambiar eje 0 y 1. De (2,3,4) -> (3,2,4)
X_01 = np.swapaxes(X, 0, 1)
print(f"X_01 shape (swap 0,1): {X_01.shape}")

# 2. Intercambiar eje 1 y 2. De (2,3,4) -> (2,4,3)
X_12 = np.swapaxes(X, 1, 2)
print(f"X_12 shape (swap 1,2): {X_12.shape}")


In [ ]:
# ### Ejercicio 11 – `transpose` con orden arbitrario
print("\n--- Ejercicio 11: transpose manual ---")
# X original (2, 3, 4) -> Ejes (0, 1, 2)

# 1. Orden (2, 0, 1). El eje 2 pasa a pos 0, eje 0 a pos 1...
# Forma esperada: (4, 2, 3)
X_201 = np.transpose(X, (2, 0, 1))
print(f"X_201 shape: {X_201.shape}")

# 2. Orden (1, 2, 0).
# Forma esperada: (3, 4, 2)
X_120 = np.transpose(X, (1, 2, 0))
print(f"X_120 shape: {X_120.shape}")
X_recuperado = np.transpose(X_120, (2, 0, 1))
print(f"X recuperado shape: {X_recuperado.shape}")
print(f"¿Es igual a X original? {np.array_equal(X, X_recuperado)}")


In [ ]:

# ### Ejercicio 12 – Uso práctico de `moveaxis`
print("\n--- Ejercicio 12: moveaxis ---")
# Imágenes: (5, 8, 6) -> (N, H, W)
images = np.random.rand(5, 8, 6)
print(f"Images shape: {images.shape}")

# Queremos formato "channels last": (N, H, W, C=1)
# Primero necesitamos añadir esa dimensión extra porque no existe.
# np.expand_dims añade un eje de tamaño 1 en la posición indicada.
images_expanded = np.expand_dims(images, axis=-1) # Añade al final
print(f"Images expanded (con canal): {images_expanded.shape}")

# Si ya tuviéramos (N, C, H, W) -> (5, 1, 8, 6) y quisiéramos mover C al final:
# images_ch_last = np.moveaxis(images_con_canal, 1, -1)

# Para este ejercicio, expandir dimensiones es la clave para conseguir el formato (5, 8, 6, 1).
images_ch_last = images_expanded 

# Volver al original quitando la dimensión extra
images_original_back = np.squeeze(images_ch_last, axis=-1)
print(f"Images back (squeeze): {images_original_back.shape}")