Ejercicio 1 - Vectorización

In [ ]:
import numpy as np

Ejercicio 1.1. Dadas dos listas de Python, lista_a y lista_b, cada una con 1.000.000 de elementos enteros aleatorios, escribe una función que calcule la suma elemento por elemento usando un bucle for de Python. Mide el tiempo de ejecución.

Ejercicio 1.2. Convierte las listas lista_a y lista_b en arrays de NumPy. Realiza la suma elemento por elemento utilizando el operador + de NumPy. Mide el tiempo de ejecución y compáralo con el del ejercicio 1.1.

Ejercicio 2 - Creación y Propiedades de Arrays para Rendimiento

Crea un array NumPy de 5000x5000 (25 millones de elementos) lleno de ceros. Realizar el ejercicio de dos maneras:
1. Usando un bucle for anidado para llenar una lista de listas y luego convertirla a un array de NumPy.
2. Usando la función np.zeros().

Ejercicio 3 - Indexación y Slicing vs. Vistas Copias

Dado el array arr = np.arange(10).
1. Crea un slice vista = arr[2:6].
2. Modifica un elemento en vista (e.g., vista[0] = 999).
3. Imprime arr y vista. ¿Qué pasó con el array original arr?
4. Ahora, crea una copia = arr[2:6].copy().
5. Modifica un elemento en la copia (e.g., copia[0] = 111).
6. Imprimir el arr y copia.

Ejerccio 4 - Creación de Arrays Básicos

Ejercicio 4.1. Crea un array 1D con los números del 0 al 9

Ejercicio 4.2. Crea un array 2D de 3x3 con todos los elementos en 1

Ejercicico 4.3. Crea un array 2x4 con números del 0 al 7

Ejecicio 4.4. Crea un array de 5 elementos espaciados uniformemente entre 0 y 1

Ejercicio 4.5. Crea un vector null(0) de tamaño 10 pero donde el quinto valor sea 1

Ejercicio 4.6. Crea un vector con valores del 100 al 300 que salte cada 4 elementos

Ejercicio 4.7. Crea una matriz de identidad de 3x3 de dos formas diferentes

Ejercicio 5 - Propiedades de Arrays

Crea un array de 3D y obtén su forma, tamaño, tipo de datos y número de dimensiones

Ejercicio 6 - Indexación Básica

Crea un array de 1D y accede mediante la indexación al primer elemento, último elemento, los elementos del 2 al 5, elementos pares e invierte los elementos del array

Ejercicio 7 - Indexación 2D

 Ejercicio 7.1. Crea un array de 2D y accede mediante la indexación al elemento [0,0], al elemento [2,1], los elementos de la primera fila y los elementos de la última columna.

In [4]:
import numpy as np
array_2d = np.array([[1,2,3],[4,5,6,],[7,8,9]])
print("Array 2D:\n", array_2d)

print("Elemento en la posición (2,1):", array_2d[2,1])
print("primer elemento: ",array_2d[0,0] )
print("ultimo elemento: ", array_2d[2,2])

Array 2D:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Elemento en la posición (2,1): 8
primer elemento:  1
ultimo elemento:  9


Ejercicio 7.2. Dadas dos matrices 2D: \
    matriz_A = np.array([[1, 2, 3], [4, 5, 6]]) \
    matriz_B = np.array([[7, 8, 9], [10, 11, 12]]) \
Realiza las siguientes operaciones usando np.append() y analiza los resultados:
- Concatenación sin axis: Aplica np.append() sin especificar el parámetro axis
- Concatenación con axis=0: Usa np.append() con axis=0 para añadir filas
- Concatenación con axis=1: Usa np.append() con axis=1 para añadir columnas

In [7]:
import numpy as np
matriz_A = np.array([[1,2,3],[4,5,6]])
    
matriz_B = np.array([[7,8,9],[10,11,12]])

juntar = np.append(matriz_A, matriz_B, axis=0)
print(juntar)
juntar2 = np.append(matriz_A, matriz_B, axis=1)
print(juntar2)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Ejerccio 8 - Operaciones aritmétricas y Funciones Matemáticas

Ejercicio 8.1. Crea dos arrays de 1D y realiza la suma, resta, multiplicación, división, potencia y raíz cuadrada

In [11]:
import numpy as np

print("-"*10)
array = np.arange(10)
array2 = np.arange(10,20)
array_sum = array + array2
print("Suma de arrays:", array_sum)
array_mul = array * array2
print("Multiplicación de arrays:", array_mul)
array_div = array2 / array
print("División de arrays:", array_div)
array_potencia = array ** 2
print("Array elevado al cuadrado:", array_potencia)

print("-"*10)

----------
Suma de arrays: [10 12 14 16 18 20 22 24 26 28]
Multiplicación de arrays: [  0  11  24  39  56  75  96 119 144 171]
División de arrays: [        inf 11.          6.          4.33333333  3.5         3.
  2.66666667  2.42857143  2.25        2.11111111]
Array elevado al cuadrado: [ 0  1  4  9 16 25 36 49 64 81]
----------


C:\Users\alere\AppData\Local\Temp\ipykernel_35220\4093065941.py:10: RuntimeWarning: divide by zero encountered in divide
  array_div = array2 / array


Ejercicio 8.2. Crea un array 1D y calcula la suma total de los elementos, la media (redondear a dos decimales), el máximo, el mínimo y la desviación estándar (redondear a dos decimales).

Ejercicio 9 - Booleanos y filtrado

Ejerccicio 9.1. Crea un array de 1D con los valores: 15, 23, 8, 42, 17, 31, 5 y 19. Determina qué elementos son: (a) mayores a 20, (b) son pares y (c) están entre 10 y 30.

Ejercicio 9.2. Modifica los elementos que sean menos a 15 y sustitúyelos por 0

Ejercicio 10 - Reshape y Transposición

Ejercicio 10.1. Crea un array 1D con arange() con valores del 0 al 11.

Ejerccio 10.2. Convierte el array 1D en un array 2D de 3 filas y 4 columnas.

Ejercicio 10.3. Transponer el array anterior de 3 filas y 4 columnas

Ejercicio 11 - Operaciones

Ejercicio 11.1. Crea un array con 5 filas y 6 columnas, con valores pseudoaleatorios del 0 al 99.

Ejercicio 11.2. Calcula la suma por filas

Ejercicio 11.3. Calcula la cuma por columnas

Ejercicio 11.4. Calcular la media global

Ejercicio 11.5. Calcular el elemento con valor máximo por columnas

Ejercicio 11.5. Determinar el índice del elemento máximo por filas

Ejercicio 12 - Operaciones matriciales

Ejercicio 12.1. Crea dos matrices de 2x2 cada una

Ejercicio 12.2. Realiza la multiplicación elemento a elemento y la multiplicación matricial

Ejercicio 12.3. Transposición y determinante de una de las matrices

Ejercicio 13 - Creación y manipulación de arrays

Ejercico 13.1. Crea dos arrays NumPy de tamaño (3,3) que contengan números enteros aleatorios entre 0 y 9. Realiza las siguientes operaciones:

1. Suma los dos arrays.
2. Encuentra el producto elemento a elemento de los dos arrays.
3. Calcula la transpuesta del primer array.
4. Encuentra el máximo valor en el segundo array.

Ejercicio 13.2. Dado el siguiente array unidimensional, reemplaza los elementos mayores que 5 por 10. \
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

Ejercicio 14 - Operaciones estadísticas

Dado un array notas que contiene las calificaciones de un grupo de estudiantes, realiza las siguientes operaciones:

1. Calcula la media de las calificaciones.
2. Encuentra la calificación más baja y la más alta.
3. Calcula la desviación estándar.

notas = np.array([7.5, 8.0, 6.2, 9.3, 5.5, 8.6, 7.0])

Ejercicio 15 - Funciones universales y operaciones vectorizadas

Dado un array x que contiene valores en el rango de 0 a 2π, realiza las siguientes operaciones:

1. Calcula el seno de cada elemento de x.
2. Calcula el coseno de cada elemento de x.
3. Utiliza las operaciones vectorizadas de NumPy para verificar la identidad trigonométrica: sin^2(𝑥)+cos^⁡2(𝑥)=1

x = np.linspace(0, 2 * np.pi, 100)