Added to the existing codes

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])		# A one dimensional NumPy array.

In [3]:
a[:2]							# From the index 0 up to the index 1 (excluding 2).

array([1, 2])

In [4]:
a[-1]

5

In [5]:
a[:5]

array([1, 2, 3, 4, 5])

In [11]:
a = np.arange(10).reshape(3,3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])	# This is a 3 x 3 two dimensional array (matrix). 

In [14]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
a[1]				# The row 1.

array([4, 5, 6])

In [15]:
a[-1]				# The last row.

array([7, 8, 9])

In [16]:
a[:]				# The whole array (matrix).

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a[:2]				# From the row 0 to the row 1 (excluding the row 2).	

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
a[2][1]			# The element from the row 2 and the column 1.	

8

In [19]:
a[2,1]			# The same as above.

8

In [20]:
a[[0, 2]]			# The rows 0 and 2.

array([[1, 2, 3],
       [7, 8, 9]])

In [21]:
a[1:, 1:]			# From the row 1 to the end. From the column 1 to the end.

array([[5, 6],
       [8, 9]])

Fancy indexing

In [22]:
arr = np.arange(100)		# A sequence from 0 to 99.

In [23]:
arrMask = ((arr % 5) == 0) 		# A Boolean array. True if multiple of 5, else False. 

In [24]:
arr[arrMask]			# Apply fancy indexing.  

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [25]:
arrMask = ( ( (arr % 5) == 0 )  & ( arr >0) )	# A Boolean array. True if multiple of 5 or 0, else False. 

In [26]:
arr[arrMask]			# Apply fancy indexing.

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

Boolean Indexing

In [27]:
test_a = np.array([1,4,0,2,3,8,9,7])

In [28]:
test_a 

array([1, 4, 0, 2, 3, 8, 9, 7])

In [22]:
#The boolean value for whether the value is greater or less than 3 among each element in test_a.

In [29]:
test_a > 3

array([False,  True, False, False, False,  True,  True,  True])

In [30]:
test_a[test_a>3] 

array([4, 8, 9, 7])