Array Transposition

In [1]:
import numpy as np

In [2]:
arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [4]:
arr=np.random.randn(6,3)
arr

array([[ 0.13762913,  0.65969708, -0.55938929],
       [ 1.18604601, -1.27526104, -0.41362218],
       [ 0.15911798,  0.64964973, -0.95517591],
       [-0.83077764, -1.17073442, -1.54610649],
       [-1.01550935,  0.77654654,  0.96116237],
       [ 0.62107825, -1.02854606,  0.3960735 ]])

In [5]:
np.dot(arr.T, arr)

array([[ 3.55815439, -1.77313166, -0.16515489],
       [-1.77313166,  5.51508633,  1.68700657],
       [-0.16515489,  1.68700657,  4.86751333]])

In [6]:
arr=np.arange(16).reshape(2,2,4)

In [7]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [8]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [9]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [9]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])