In [5]:
#pregunta 1
import numpy as np
# Zero vector
zero_vector = np.zeros((3,))
print("Zero Vector: ")
print()
print( zero_vector)

# One vector
one_vector = np.ones((3,))
print("One Vector: ")
print()
print( one_vector)

# Square matrix
square_matrix = np.array([[5, 3], [10, 2]])
print("Square Matrix: ")
print()
print( square_matrix)

# Diagonal matrix
diagonal_matrix = np.diag([1, 2, 3])
print("Diagonal Matrix: ")
print()
print( diagonal_matrix)

# Identity matrix
identity_matrix = np.eye(3)
print("Identity Matrix: ")
print()
print( identity_matrix)

# Symmetric matrix
symmetric_matrix = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]])
print("Symmetric Matrix: ")
print()
print( symmetric_matrix)




Zero Vector: 

[0. 0. 0.]
One Vector: 

[1. 1. 1.]
Square Matrix: 

[[ 5  3]
 [10  2]]
Diagonal Matrix: 

[[1 0 0]
 [0 2 0]
 [0 0 3]]
Identity Matrix: 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Symmetric Matrix: 

[[1 2 3]
 [2 4 5]
 [3 5 6]]


In [9]:
#pregunta numero 2
#1
p = np.array([100, 80, 50])
n = np.array([3, 4, 5])
print("Precio del Vector (p): ")
print(p)
print("Cantidad del Vector (n): ")
print(n)
print()



Precio del Vector (p): 
[100  80  50]
Cantidad del Vector (n): 
[3 4 5]



In [10]:
#2	
total_amount = np.dot(p, n)
print("Cantidad total requerida para comprar acciones: ")
print(total_amount)

Cantidad total requerida para comprar acciones: 
870


In [ ]:
from sklearn.datasets import load_digits
import numpy as np

X = load_digits().data


similitud = np.dot(X[0], X[9])
print("Similitud imagen 1 y 10:", similitud)

matriz_similitud = np.dot(X, X.T)
print("Matriz completa:\n", matriz_similitud)

In [ ]:
import pandas as pd
import numpy as np

def load_boston():
    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]
    return {'data': data, 'target': target}

boston = load_boston()
X = boston['data']
y = boston['target']

A = X[:4, [0, 4, 5, 6]] 
b = y[:4]

A_inv = np.linalg.inv(A)
x = np.dot(A_inv, b)

print(x)



In [ ]:
import pandas as pd
import numpy as np

def load_boston():
    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]
    return {'data': data, 'target': target}


boston=load_boston()
X=boston[‘data’]
y=boston[‘target’]


In [ ]:
import numpy as np

a = np.array([4, 5, 2, 2])
b = np.array([4, 0, 2, 0])
c = np.array([2, 2, 0, 1])

print(np.linalg.norm(a - b))
print(np.linalg.norm(b - c))
print(np.linalg.norm(c - a))

5.385164807134504
3.605551275463989
4.242640687119285


In [3]:
cos_ab = 1 - np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
cos_bc = 1 - np.dot(b, c) / (np.linalg.norm(b) * np.linalg.norm(c))
cos_ca = 1 - np.dot(c, a) / (np.linalg.norm(c) * np.linalg.norm(a))

print(cos_ab)
print(cos_bc)
print(cos_ca)

0.36112343500006017
0.40371520600005606
0.04761904761904767


In [ ]:
import numpy as np

D = np.array([[2, 1], [1, 2]])
eigenvalues, eigenvectors = np.linalg.eig(D)
print(eigenvalues) 


[3. 1.]


In [4]:
import numpy as np

print(np.log(12))

2.4849066497880004


In [ ]:
import sympy

x = sympy.symbols('x')
f = x**3 - 1
print(sympy.diff(f))

x, k = sympy.symbols('x k')
f = sympy.log(x**2 - 3*k)
print(sympy.diff(f, x))

x, a, b = sympy.symbols('x a b')
f = sympy.exp(a * x**b)
print(sympy.simplify(sympy.diff(f, x)))

In [ ]:
import sympy

x, y = sympy.symbols('x y')
f = sympy.exp(x**2 + 2*y**2)

print(sympy.diff(f, x))
print(sympy.diff(f, y))
print(sympy.diff(f, x, x))
print(sympy.diff(f, x, y))
print(sympy.diff(f, y, x))
print(sympy.diff(f, y, y))