## Coding Exercise #0513

In [1]:
import numpy as np
import warnings
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition  import LatentDirichletAllocation
warnings.filterwarnings('ignore')

#### 1. Latent Dirichlet Allocation (LDA):

In [2]:
# The data.
my_docs = ["The economic slowdown is becoming more severe",
           "The movie was simply awesome",
           "I like cooking my own food",
           "Samsung is announcing a new technology",
           "Machine Learning is an example of awesome technology",
           "All of us were excited at the movie",
           "We have to do more to reverse the economic slowdown"]

In [3]:
my_docs = [x.lower() for x in my_docs]

#### 1.1. Create a DTM representation:
CountVectorizer() arguments: <br>
- *max_features* : maximum number of features (distict words). <br>
- *min_df* : The minimum DF. Integer value means count and real number (0~1) means proportion. <br> 
- *max_df* : The maximum DF. Integer value means count and real number (0~1) means proportion. Helps to filter out the stop words. <br> 

In [4]:
vectorizer = CountVectorizer(max_features = 15, min_df = 1, max_df = 3, stop_words = list(ENGLISH_STOP_WORDS))
X = vectorizer.fit_transform(my_docs).toarray()               

In [5]:
# Show th DTM. 
X

array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0]])

In [ ]:
# Size of X (=m x n). m = number of documents = 7 & n = number of features.

X.shape

(7, 15)

In [ ]:
# View the features.
features = vectorizer.get_feature_names_out()
print(features)
#features hace referencia a las palabras o términos que se han extraído del conjunto de documentos 
# y que se utilizan como características en el modelo de aprendizaje automático. Estas características 
# representan la presencia o frecuencia de cada término en los documentos, y son utilizadas para construir 
# la matriz de términos-documentos (DTM) que se alimenta al modelo para el análisis de temas o clasificación.

['announcing' 'awesome' 'economic' 'example' 'excited' 'food' 'learning'
 'like' 'machine' 'movie' 'new' 'reverse' 'samsung' 'slowdown'
 'technology']


#### 1.2. Apply the LDA: 

In [8]:
# Get the topics.
n_topics = 4
lda = LatentDirichletAllocation(n_components=n_topics, random_state=123)
my_docs_topic = lda.fit_transform(X)                               

In [9]:
# row = document, column = topic.
my_docs_topic

array([[0.74970373, 0.08344895, 0.0833985 , 0.08344882],
       [0.08450153, 0.08665021, 0.08339073, 0.74545753],
       [0.08340423, 0.08351543, 0.74956511, 0.08351523],
       [0.05060012, 0.05010115, 0.84919768, 0.05010105],
       [0.8723624 , 0.04178666, 0.04252583, 0.04332511],
       [0.08337347, 0.74650649, 0.08339086, 0.08672918],
       [0.81219992, 0.06261703, 0.06256614, 0.0626169 ]])

In [10]:
# Sum along the row has to give 1.
my_docs_topic.sum(axis=1)

array([1., 1., 1., 1., 1., 1., 1.])

#### 1.3. From each topic, extract the top features:

In [11]:
topic_composition = lda.components_
topic_composition.shape     # row = topic, column = feature (word).

(4, 15)

In [12]:
n_top = 3
for i in range(n_topics):
    topic_features = [features[idx] for idx in np.argsort(-topic_composition[i,:])]   # argsort() shows the sorted index.
    topic_features_top = topic_features[0:n_top]
    if i == 0:
        topic_matrix = [topic_features_top]                    # list의 list 만들 준비!
    else:
        topic_matrix.append(topic_features_top) 

In [18]:
# Show the top features for each topic.
topic_matrix

[['economic', 'slowdown', 'learning'],
 ['movie', 'excited', 'awesome'],
 ['technology', 'announcing', 'new'],
 ['awesome', 'movie', 'technology']]

In [20]:
# In view of the top features, we can name the topics.
topic_names = ['Technology', 'Cuisine', 'Movie','Economy']

#### 1.4. Label each document with the most predominant topic:

In [22]:
# The most probable topic is given directly by the LDA output.
n_docs = len(my_docs)
for i in range(n_docs):
    topic_pick = np.argmax(my_docs_topic[i,:])
    print("Document " + str(i+1) + " = " + topic_names[topic_pick])

Document 1 = Technology
Document 2 = Economy
Document 3 = Movie
Document 4 = Movie
Document 5 = Technology
Document 6 = Cuisine
Document 7 = Technology


**NOTE**: We can notice some inaccuracies.