In [1]:
import numpy as np
import time

# 1. Demostración de Operaciones
print("--- 1. Operaciones Elemento-a-Elemento vs. Concatenación ---")
list_a = [1, 2, 3]
list_b = [10, 20, 30]

# Python Listas (List)
list_sum = list_a + list_b
list_mult = 2 * list_a
print(f"Listas: {list_a} + {list_b} = {list_sum} (¡Estructura: Concatenación!)")
print(f"Listas: 2 * {list_a} = {list_mult} (¡Estructura: Repetición!)")

# NumPy Arrays (ndarray)
array_a = np.array(list_a)
array_b = np.array(list_b)
array_sum = array_a + array_b
array_mult = 2 * array_a
print(f"Arrays: {array_a} + {array_b} = {array_sum} (Matemática: Suma elemento-a-elemento)")
print(f"Arrays: 2 * {array_a} = {array_mult} (Matemática: Multiplicación elemento-a-elemento)")
print("-" * 60)

# 2. Demostración de Velocidad (Vectorización)
# Generamos un millón de elementos (como en el PDF)
SIZE = 1_000_000
ITERATIONS = 100 

np_array = np.arange(SIZE)
py_list = list(range(SIZE))

print(f"--- 2. Ventaja de Velocidad (Vectorización) ---")
print(f"Comparando 1 millón de elementos, repetido {ITERATIONS} veces.")

# Medición de tiempo para NumPy (Vectorización)
np_start = time.time()
for _ in range(ITERATIONS):
    np_array * 2 # Operación vectorizada implementada en C [cite: 428, 1169]
np_time = time.time() - np_start

# Medición de tiempo para Listas de Python (Comprensión de lista para simular elemento-a-elemento)
py_start = time.time()
for _ in range(ITERATIONS):
    [x * 2 for x in py_list] # Requiere el intérprete de Python y un bucle explícito
py_time = time.time() - py_start

print(f"Tiempo NumPy: {np_time:.5f} segundos")
print(f"Tiempo Python List: {py_time:.5f} segundos")

if np_time > 0:
    speed_factor = py_time / np_time
    print(f"\n¡NumPy es aproximadamente {speed_factor:.1f} veces más rápido! 🚀")

--- 1. Operaciones Elemento-a-Elemento vs. Concatenación ---
Listas: [1, 2, 3] + [10, 20, 30] = [1, 2, 3, 10, 20, 30] (¡Estructura: Concatenación!)
Listas: 2 * [1, 2, 3] = [1, 2, 3, 1, 2, 3] (¡Estructura: Repetición!)
Arrays: [1 2 3] + [10 20 30] = [11 22 33] (Matemática: Suma elemento-a-elemento)
Arrays: 2 * [1 2 3] = [2 4 6] (Matemática: Multiplicación elemento-a-elemento)
------------------------------------------------------------
--- 2. Ventaja de Velocidad (Vectorización) ---
Comparando 1 millón de elementos, repetido 100 veces.
Tiempo NumPy: 0.25152 segundos
Tiempo Python List: 9.63495 segundos

¡NumPy es aproximadamente 38.3 veces más rápido! 🚀


In [ ]:
import numpy as np

arr1 = np.array([2, 4, 6])
arr2 = np.array([1, 2, 3])

# Multiplicación elemento a elemento
mult_element_wise = arr1 * arr2 
# Resultado: [2*1, 4*2, 6*3] = [2, 8, 18]
print(mult_element_wise)

# Operación compleja elemento a elemento
complex_op = (arr1 + 10) / arr2
# Resultado: [(2+10)/1, (4+10)/2, (6+10)/3] = [12.0, 7.0, 5.3333...]

[ 2  8 18]
[12.          7.          5.33333333]


In [ ]:
import numpy as np

# Definimos una lista con 2 números (int) y 1 texto (str)
mi_data = [1, 2, '¡ALERTA!']

# Creamos el array de NumPy
array_mixto = np.array(mi_data)

# Imprimimos el array y su tipo de dato (dtype)
print("Array creado:", array_mixto)
print("Tipo de dato de los elementos (dtype):", array_mixto.dtype)
#Tipo de dato de los elementos (dtype): <U7: Todo el array ahora 
#tiene el tipo Unicode String (<U7), ya no son números.

# ¿Intentemos una operación matemática (suma)?
print("\nResultado de sumar 10:", array_mixto + '10')

Array creado: ['1' '2' '¡ALERTA!']
Tipo de dato de los elementos (dtype): <U21

Resultado de sumar 10: ['110' '210' '¡ALERTA!10']


In [9]:
# A. Crear un array 1D (vector)
mi_lista = [10, 20, 30, 40, 50]
mi_array_1d = np.array(mi_lista)

print("1. Array creado:", mi_array_1d)
print("2. Tipo de objeto:", type(mi_array_1d)) # Debería ser <class 'numpy.ndarray'>
print("3. Dimensión (ndim):", mi_array_1d.ndim) # Debería ser 1
print("4. Identificador único (id):", id(mi_array_1d))
#el id es un número único que identifica el objeto en memoria.


1. Array creado: [10 20 30 40 50]
2. Tipo de objeto: <class 'numpy.ndarray'>
3. Dimensión (ndim): 1
4. Identificador único (id): 2853917528816


In [11]:
import numpy as np

# Definimos una matriz (lista de listas)
matriz_data = [[1, 2, 3], 
               [4, 5, 6]]

# Creamos el array 2D
mi_array_2d = np.array(matriz_data)

print("Array 2D:\n", mi_array_2d)
print("--------------------------")
print(f"Dimensiones (ndim): {mi_array_2d.ndim}") 
#ndim indica el número de ejes (dimensiones) del array.
print(f"Forma (shape - Filas, Columnas): {mi_array_2d.shape}")
#shape es una tupla que indica el tamaño del array en cada dimensión (filas, columnas).
print(f"Total de elementos (size): {mi_array_2d.size}")
#size indica el número total de elementos en el array.

Array 2D:
 [[1 2 3]
 [4 5 6]]
--------------------------
Dimensiones (ndim): 2
Forma (shape - Filas, Columnas): (2, 3)
Total de elementos (size): 6


In [12]:
import numpy as np

# Creación de array desde una lista
arr1 = np.array([1, 3, 5, 7, 9])
print("Array arr1:", arr1)

# Comprobar el tipo de objeto
print("Tipo de arr1:", type(arr1))

Array arr1: [1 3 5 7 9]
Tipo de arr1: <class 'numpy.ndarray'>


In [13]:
# arr1 ya está definido del código anterior

# Asignación de dirección (comparten la misma memoria)
arr3 = arr1
print("\nIDs de Memoria después de arr3 = arr1:")
print("ID de arr1:", id(arr1))
print("ID de arr3:", id(arr3)) # El ID es el mismo [cite: 530-531]

# Copia de valor (crea una nueva dirección de memoria)
arr4 = np.copy(arr1)
print("\nIDs de Memoria después de arr4 = np.copy(arr1):")
print("ID de arr1:", id(arr1))
print("ID de arr4:", id(arr4)) # El ID es diferente [cite: 569]


IDs de Memoria después de arr3 = arr1:
ID de arr1: 2853917527472
ID de arr3: 2853917527472

IDs de Memoria después de arr4 = np.copy(arr1):
ID de arr1: 2853917527472
ID de arr4: 2853917531216


In [15]:
# Creación con np.arange (similar a range en Python)
a = np.arange(1, 10, 2)
print("\nArray 'a' (np.arange(1, 10, 2)):", a)

# Crear un array 2D
a2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\nArray 2D a2d:\n", a2d)

# Propiedades del array a2d
print("Total de elementos (.size):", a2d.size)    # 6 elementos [cite: 938-940]
print("Forma (Filas, Columnas) (.shape):", a2d.shape) # 2 filas, 3 columnas [cite: 942-944]
print("Número de dimensiones (.ndim):", a2d.ndim)  # Es bidimensional [cite: 945-946]


Array 'a' (np.arange(1, 10, 2)): [1 3 5 7 9]

Array 2D a2d:
 [[1 2 3]
 [4 5 6]]
Total de elementos (.size): 6
Forma (Filas, Columnas) (.shape): (2, 3)
Número de dimensiones (.ndim): 2


In [18]:
# Crear un array 2D de ceros (2 filas, 3 columnas)
arr2dZero = np.zeros((9, 7))
print("\nArray de Ceros 2x3:\n", arr2dZero) # Por defecto, los elementos son float [cite: 897]

# Creación de secuencia 1D de 15 elementos
a2 = np.arange(15)
print("\nArray a2 original (1D):", a2)

# Reorganizar a 3 filas y 5 columnas
a2_reshaped = a2.reshape((3, 5))
print("\nArray a2 reorganizado (3x5):\n", a2_reshaped)

# La forma se puede cambiar directamente (forma alternativa)
a3 = np.arange(15)
a3.shape = (5, 3)
print("\nArray a3 con forma cambiada directamente (5x3):\n", a3)


Array de Ceros 2x3:
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

Array a2 original (1D): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Array a2 reorganizado (3x5):
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Array a3 con forma cambiada directamente (5x3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
# Dos bloques 2x2. Piénsalo como 2 "páginas" apiladas.
data3d = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
arr3d = np.array(data3d)

print("Array 3D Creado:\n", arr3d)
print("--------------------------")
#posicion adelante
print(data3d[0])
#posicion atras
print(data3d[1])
print("--------------------------")
print(f"Dimensiones (.ndim): {arr3d.ndim}")    # Resultado: 3 [cite: 875-877]
print(f"Forma (.shape): {arr3d.shape}")        # Resultado: (2, 2, 2)

[[1, 2], [3, 4]]
[[5, 6], [7, 8]]
Array 3D Creado:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
--------------------------
Dimensiones (.ndim): 3
Forma (.shape): (2, 2, 2)


In [27]:
import numpy as np

a = np.array([1, 2, 3])

# Añadir elementos a un array 1D
b = np.append(a, [4, 5, 6])
print("Array b después de append:", b)

# El array original 'a' no cambia
print("Array original 'a':", a)
# (Tienes que reasignar el resultado a una variable para que persistan los cambios) [cite: 1195]

Array b después de append: [1 2 3 4 5 6]
Array original 'a': [1 2 3]


In [28]:
import numpy as np

# 1. Array 2D base (2 filas, 2 columnas)
a = np.array([[1, 2], [3, 4]])
print("Array base 'a' (2x2):\n", a)

# 2. Agregar una nueva FILA (axis=0)
# Se añade como una nueva lista de listas [[9, 9]]
b = np.append(a, [[9, 9]], axis=0)
print("\nArray 'b' (Añadir FILA con axis=0):\n", b) 

# 3. Agregar una nueva COLUMNA (axis=1)
# Se añade como dos listas de un solo elemento [[9], [9]]
c = np.append(a, [[9], [9]], axis=1)
print("\nArray 'c' (Añadir COLUMNA con axis=1):\n", c)

Array base 'a' (2x2):
 [[1 2]
 [3 4]]

Array 'b' (Añadir FILA con axis=0):
 [[1 2]
 [3 4]
 [9 9]]

Array 'c' (Añadir COLUMNA con axis=1):
 [[1 2 9]
 [3 4 9]]


In [30]:
#usaremos la funcion full 
arr2dZero = np.zeros((9, 7))
print("\nArray de Ceros 9x7:\n", arr2dZero)
# saber las dimensiones del array
print(f"Dimensiones (.ndim): {arr2dZero.ndim}")    # Resultado: 2
print(f"Forma (.shape): {arr2dZero.shape}")        # Resultado: (9, 7)
print(f"Total de elementos (.size): {arr2dZero.size}")    # Resultado
    



Array de Ceros 9x7:
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
Dimensiones (.ndim): 2
Forma (.shape): (9, 7)
Total de elementos (.size): 63


In [31]:
import numpy as np

arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])

# Unir arr_a y arr_b
resultado_1d = np.concatenate((arr_a, arr_b))

print("Arrays a unir:", arr_a, "y", arr_b)
print("Resultado 1D:", resultado_1d)

Arrays a unir: [1 2 3] y [4 5 6]
Resultado 1D: [1 2 3 4 5 6]


In [34]:
# Dos matrices 2x2
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

# Unir Verticalmente (añadir filas)
resultado_v = np.concatenate((matriz1, matriz2), axis=0)
print("\nArrays a unir:")
print("matriz1:")
print(matriz1)
print("matriz2:")
print(matriz2)

print("\n--- Unir con axis=0 (Filas) ---")
print("Resultado 4x2:\n", resultado_v)
# La forma resultante es (4, 2)


Arrays a unir:
matriz1:
[[1 2]
 [3 4]]
matriz2:
[[5 6]
 [7 8]]

--- Unir con axis=0 (Filas) ---
Resultado 4x2:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [36]:
import numpy as np

# M1: 2 Filas, 3 Columnas (Nombre, Nota1, Nota2)
M1 = np.array([[10, 80, 90], 
               [11, 75, 85]]) 

# M2: Otro grupo de alumnos (también 3 columnas)
M2 = np.array([[12, 95, 99]]) 

# M3: Nuevas características (debe tener 2 filas, para coincidir con M1)
M3 = np.array([[100], 
               [110]]) 

# --- TAREA A: Añadir más FILAS (Alumnos) ---
# Usamos axis=0. Ambas matrices tienen 3 columnas.
resultado_filas = np.concatenate((M1, M2), axis=0) 
print("1. Concatenar FILAS (axis=0):\n", resultado_filas) 
# Resultado: 3 filas, 3 columnas. (Añadiste una fila al final)

# --- TAREA B: Añadir más COLUMNAS (Características) ---
# Usamos axis=1. Ambas matrices tienen 2 filas.
resultado_columnas = np.concatenate((M1, M3), axis=1) 
print("\n2. Concatenar COLUMNAS (axis=1):\n", resultado_columnas) 
# Resultado: 2 filas, 4 columnas. (Añadiste una columna al final)

1. Concatenar FILAS (axis=0):
 [[10 80 90]
 [11 75 85]
 [12 95 99]]

2. Concatenar COLUMNAS (axis=1):
 [[ 10  80  90 100]
 [ 11  75  85 110]]


In [37]:
import numpy as np

# M2: 1 Filas, 3 Columnas (Shape: (1, 3))
M2 = np.array([[12, 95, 99]]) 

# M3: 2 Filas, 1 Columna (Shape: (2, 1))
M3 = np.array([[100], 
               [110]]) 

print(f"M2 shape: {M2.shape}")
print(f"M3 shape: {M3.shape}")

# Intento fallido de concatenar M2 y M3
try:
    np.concatenate((M2, M3), axis=0)
except ValueError as e:
    print(f"\nIntento axis=0 (Añadir FILAS): FALLÓ.")
    print(f"ERROR: {e}")

try:
    np.concatenate((M2, M3), axis=1)
except ValueError as e:
    print(f"\nIntento axis=1 (Añadir COLUMNAS): FALLÓ.")
    print(f"ERROR: {e}")

M2 shape: (1, 3)
M3 shape: (2, 1)

Intento axis=0 (Añadir FILAS): FALLÓ.
ERROR: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 1

Intento axis=1 (Añadir COLUMNAS): FALLÓ.
ERROR: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 2


In [38]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Operaciones básicas
print("Suma (arr1 + arr2):", arr1 + arr2)      # [5 7 9] [cite: 1335]
print("Resta (arr1 - arr2):", arr1 - arr2)     # [-3 -3 -3] [cite: 1358]
print("Multiplicación (arr1 * arr2):", arr1 * arr2) # [4 10 18] [cite: 1359]
print("Exponencial (arr2 ** 2):", arr2 ** 2)    # [16 25 36] [cite: 1442]

Suma (arr1 + arr2): [5 7 9]
Resta (arr1 - arr2): [-3 -3 -3]
Multiplicación (arr1 * arr2): [ 4 10 18]
Exponencial (arr2 ** 2): [16 25 36]


In [39]:
arr3 = np.array([10, 20, 30, 40])
# ¿Qué elementos son mayores que 10?
print("Comparación (arr3 > 10):", arr3 > 10) # [False True True True] [cite: 1463-1464]

Comparación (arr3 > 10): [False  True  True  True]


In [40]:
# Array original
a = np.array([1, 2, 3, 4, 5, 6])

# Condición: Array booleano que devuelve True o False para cada elemento
filtro = (a > 3) # [False, False, False, True, True, True]

# Indexación Booleana: Solo devuelve donde el filtro es True
elementos_filtrados = a[filtro]
print("Elementos filtrados (a > 3):", elementos_filtrados) # [4, 5, 6] [cite: 1755]

Elementos filtrados (a > 3): [4 5 6]


In [41]:
A = np.array([[1, 2], [3, 4]])
A_transpuesta = A.T

print("A.shape:", A.shape)     # (2, 2)
print("A.T.shape:", A_transpuesta.shape) # (2, 2)

A.shape: (2, 2)
A.T.shape: (2, 2)
