In [ ]:
#crear dos arrays con 1 millon de elentos aleaatorios 
import numpy as np
array1 = np.random.rand(1000000)
array2 = np.random.rand(1000000)
#y solo mostrar 5 primeros elementos 
print("Primeros 5 elementos del array1:", array1[:5])
print("Primeros 5 elementos del array2:", array2[:5])

#funcion para sumar elemento por elemenot 
import time


def suma(lista1,lista2):
    resultado = []
    for i in range(len(lista1)):
        suma = lista1[i] + lista2[i]
        resultado.append(suma)
    return resultado
#mostrar solo 5 primeros elementos de la lista
start_time = time.time()
resultado_suma = suma(array1, array2)
end_time = time.time()
print("Tiempo de ejecucion de la suma elemento por elemento: %s segundos" % (end_time - start_time))    


suma(array1, array2)


In [2]:
import numpy as np
import time

lista_a = list(range(1000000))
lista_b = list(range(1000000))

array_a = np.array(lista_a)
array_b = np.array(lista_b)

print("--- INICIO ---")

inicio_manual = time.time()
resultado_manual = []
for i in range(len(lista_a)):
    suma = lista_a[i] + lista_b[i]
    resultado_manual.append(suma)
fin_manual = time.time()
#mostrar lo 5 primeros elementos de cada resultado
print("Primeros 5 elementos resultado manual:", resultado_manual[:5])
print("Primeros 5 elementos resultado NumPy:", (array_a + array_b)[:5])
print(f"Tiempo Manual: {fin_manual - inicio_manual:.5f} segundos")

inicio_numpy = time.time()
resultado_numpy = array_a + array_b
fin_numpy = time.time()
print(f"Tiempo NumPy:  {fin_numpy - inicio_numpy:.5f} segundos")

--- INICIO ---
Primeros 5 elementos resultado manual: [0, 2, 4, 6, 8]
Primeros 5 elementos resultado NumPy: [0 2 4 6 8]
Tiempo Manual: 0.36512 segundos
Tiempo NumPy:  0.00677 segundos


In [ ]:
#crea un array numpy de 5000 x 5000 25 millones de elementos llenos de 0 
#realizar el ejericio de dos maneros 
# usando un buble for anidado para llena runa lista de listas y luego convertirla a un array de numpy 
#usando unfcion np.zeros
import numpy as np
import time

array_size = 5000

print(f"--- INICIO: Creando matriz de {array_size}x{array_size} ---")

# ---------------------------------------------------------
# FORMA 1: Bucle For Anidado (La forma "Manual")
# ---------------------------------------------------------
start_manual = time.time()

lista_de_listas = []
for i in range(array_size):
    fila = []
    for j in range(array_size):
        fila.append(0)     # Agregamos el 0 uno por uno
    lista_de_listas.append(fila)

# Convertimos esa lista gigante a NumPy (esto también tarda)
array1 = np.array(lista_de_listas)

end_manual = time.time()
tiempo_manual = end_manual - start_manual
print(f"Tiempo Bucle For: {tiempo_manual:.5f} segundos")


# ---------------------------------------------------------
# FORMA 2: np.zeros (La forma NumPy)
# ---------------------------------------------------------
start_numpy = time.time()

# np.zeros reserva la memoria de golpe. No itera en Python.
array2 = np.zeros((array_size, array_size))

end_numpy = time.time()
tiempo_numpy = end_numpy - start_numpy
print(f"Tiempo np.zeros:  {tiempo_numpy:.5f} segundos")


# ---------------------------------------------------------
# CONCLUSIÓN
# ---------------------------------------------------------
if tiempo_numpy > 0:
    velocidad = tiempo_manual / tiempo_numpy
    print(f"\nNumPy fue {velocidad:.0f} veces más rápido.")
else:
    print("\nNumPy fue instantáneo (0.00 segundos).")

# Verificación rápida de que son iguales en forma
print(f"\nForma Array 1: {array1.shape}")
print(f"Forma Array 2: {array2.shape}")



Array creado usando bucle for anidado: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Array creado usando np.zeros: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [4]:
import numpy as np

# 0. Creamos el array base
arr = np.arange(10)
print(f"Inicio: {arr}")

# --- PARTE 1: VISTA (Modifica el original) ---
vista = arr[2:6]        # Esto es solo una ventana, no un array nuevo
vista[0] = 999          # Cambiamos el primer valor de la vista

print("\n--- VISTA ---")
print(f"Vista: {vista}")
print(f"Arr:   {arr}")  # ¡OJO! El 999 apareció aquí también

# --- PARTE 2: COPIA (Independiente) ---
copia = arr[2:6].copy() # .copy() crea un array nuevo en memoria
copia[0] = 111          # Cambiamos la copia

print("\n--- COPIA ---")
print(f"Copia: {copia}")
print(f"Arr:   {arr}")  # El original NO cambia (sigue con el 999 de antes)

Inicio: [0 1 2 3 4 5 6 7 8 9]

--- VISTA ---
Vista: [999   3   4   5]
Arr:   [  0   1 999   3   4   5   6   7   8   9]

--- COPIA ---
Copia: [111   3   4   5]
Arr:   [  0   1 999   3   4   5   6   7   8   9]


In [5]:
nuevecito = np.arange(10)
print(nuevecito)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
#crear un arrray de 3 dimensiones y obtener su forma, tamaño, tipo de datos, numero de dimensiones
import numpy as np
array_3d = np.random.rand(4, 3, 2)  # Array de 3 dimensiones
print("Array 3D:\n", array_3d)
print("Forma del array:", array_3d.shape)
print("Tamaño del array:", array_3d.size)
print("Tipo de datos del array:", array_3d.dtype)
print("Número de dimensiones del array:", array_3d.ndim)


Array 3D:
 [[[0.21860645 0.37689276]
  [0.20698105 0.92945019]
  [0.66859722 0.30585012]]

 [[0.67074963 0.36489225]
  [0.53918624 0.29094411]
  [0.27303226 0.10572185]]

 [[0.42876551 0.70753758]
  [0.95837567 0.51640019]
  [0.54768539 0.54126868]]

 [[0.66486978 0.03288253]
  [0.1858728  0.79476978]
  [0.15451735 0.03549442]]]
Forma del array: (4, 3, 2)
Tamaño del array: 24
Tipo de datos del array: float64
Número de dimensiones del array: 3
